apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: &name connector
  labels: 
    app: *name
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: *name
  minReplicas: 1
  maxReplicas: 16
  metrics:
    - type: External
      external:
        metricName: pubsub.googleapis.com|subscription|num_undelivered_messages
        metricSelector:
          matchLabels:
            resource.labels.subscription_id: app-sub
        targetAverageValue: 30000
